# Generated by Django 5.2.17 on 2026-09-23 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='SJR Stories', max_length=100)),
                ('heading', models.TextField(help_text='e.g. See SJR Groups in motion.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Videos Section',
                'verbose_name_plural': 'Videos Section',
            },
        ),
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='videos/')),
                ('label', models.CharField(help_text='e.g. Our Story, or Fashion Shelter', max_length=100)),
                ('title', models.CharField(help_text='e.g. The world of SJR Groups', max_length=150)),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Instagram link')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as the large featured video')),
                ('order', models.PositiveIntegerField(default=0)),
                ('videos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='videos.videos')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
