# Generated by Django 5.2.17 on 2026-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload the video file (mp4 recommended) to play it directly on the site', null=True, upload_to='videos/files/'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Used only if no video file is uploaded — a YouTube/Instagram link instead'),
        ),
    ]
