# Generated by Django 5.2.17 on 2026-09-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, help_text='e.g. Fashion · Tradition · Fitness', max_length=150)),
                ('heading', models.TextField(help_text='e.g. Discover the world of SJR Groups.')),
                ('cta_text', models.CharField(blank=True, help_text='e.g. Explore Our Businesses', max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Banner Section',
                'verbose_name_plural': 'CTA Banner Section',
            },
        ),
    ]
