# Generated by Django 5.2.17 on 2026-09-23 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='Contact SJR Groups', max_length=100)),
                ('heading', models.TextField(help_text="e.g. Let's connect.")),
                ('description', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL')),
                ('map_link', models.URLField(blank=True, help_text='"View on Google Maps" button link')),
                ('location_label', models.CharField(blank=True, help_text='e.g. Kovilpatti', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Call, WhatsApp, Email', max_length=50)),
                ('value', models.CharField(help_text='e.g. Official number coming soon, or the actual number/email', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='contact.contact')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
