# Generated by Django 5.2.17 on 2026-09-23 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='The SJR Standard', max_length=100)),
                ('heading', models.TextField(help_text='e.g. More than businesses. A growing family.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SJR Standard Section',
                'verbose_name_plural': 'SJR Standard Section',
            },
        ),
        migrations.CreateModel(
            name='StandardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Quality', max_length=100)),
                ('description', models.CharField(blank=True, help_text='e.g. Committed to delivering value.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='standard.standard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
