# Generated by Django 5.2.17 on 2026-09-23 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='05 / Customer Stories', max_length=100)),
                ('heading', models.TextField(help_text='e.g. What our customers say.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reviews Section',
                'verbose_name_plural': 'Reviews Section',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('business_location', models.CharField(blank=True, help_text='e.g. Business / Location', max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reviews.reviews')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
