# Generated by Django 5.2.17 on 2026-09-23 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='Our Businesses', max_length=100)),
                ('heading', models.TextField(help_text='e.g. Four brands. One identity.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Businesses Section',
                'verbose_name_plural': 'Businesses Section',
            },
        ),
        migrations.CreateModel(
            name='BusinessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/')),
                ('title', models.CharField(help_text='e.g. Fashion Shelter / Covering Jewellery', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Style That Shines.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='One feature per line, e.g. Trendy Collections')),
                ('cta_text', models.CharField(blank=True, help_text='e.g. Explore on Fashion Shelter', max_length=50)),
                ('cta_link', models.CharField(blank=True, max_length=255)),
                ('accent_color', models.CharField(blank=True, help_text='Hex color for this brand, e.g. #8B5E34', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='business.business')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
