# Generated by Django 5.2.17 on 2026-09-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='header/')),
                ('brand_name', models.CharField(default='SJR GROUPS', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('cta_text', models.CharField(blank=True, default='Connect With Us', max_length=50)),
                ('cta_link', models.CharField(blank=True, default='#contact', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header & Navigation',
                'verbose_name_plural': 'Header & Navigation',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('link', models.CharField(help_text='URL or anchor, e.g. #about or /about/', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='header_navigation.header')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
