# Generated by Django 5.2.17 on 2026-09-23 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='About SJR Groups', max_length=100)),
                ('heading', models.TextField(help_text='Supports line breaks, e.g. "Building businesses.\\nCreating experiences."')),
                ('description_primary', models.TextField(blank=True)),
                ('description_secondary', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Four Businesses', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.about')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
