# Generated by Django 5.2.17 on 2026-09-23 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(blank=True, default='Stay Connected', max_length=100)),
                ('heading', models.TextField(help_text='e.g. Follow the SJR Groups journey.')),
                ('description', models.TextField(blank=True, default='Official social channels will be connected here once supplied by the SJR Groups team.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stay Connected Section',
                'verbose_name_plural': 'Stay Connected Section',
            },
        ),
        migrations.CreateModel(
            name='SocialFeaturedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='social/')),
                ('label', models.CharField(help_text='e.g. Fashion Shelter', max_length=100)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_cards', to='social.social')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Facebook, Instagram, YouTube', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='social.social')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
