# Generated by Django 5.2.17 on 2026-09-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('brand_name', models.CharField(blank=True, default='SJR GROUPS', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='e.g. One Vision · Endless Possibilities', max_length=150)),
                ('description', models.CharField(blank=True, help_text='e.g. One Group. Four Unique Businesses.', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='e.g. Coming soon', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.TextField(blank=True, help_text='Full address')),
                ('copyright_text', models.CharField(blank=True, default='© 2026 SJR Groups. All Rights Reserved.', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('quick_links', 'Quick Links'), ('businesses', 'Our Businesses')], default='quick_links', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='footer.footer')),
            ],
            options={
                'ordering': ['column', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. Facebook, Instagram, YouTube', max_length=50)),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='footer.footer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
