# Generated by Django 5.2.17 on 2026-09-23 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. One Vision · Four Businesses · Endless Possibilities', max_length=150)),
                ('heading', models.TextField(help_text='Supports line breaks, e.g. "One group.\\nFour unique businesses."')),
                ('description', models.TextField(blank=True)),
                ('primary_cta_text', models.CharField(blank=True, max_length=50)),
                ('primary_cta_link', models.CharField(blank=True, max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, max_length=50)),
                ('secondary_cta_link', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='hero.hero')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
